module.exports = function(grunt) {
  grunt.initConfig({
    includes: {
      build: {
        cwd: '../',
        src: [ 'docs/index.apib' ],
        dest: 'test/',
        options: {
          includeRegexp: /<!-- include\(([^'"]+)\) -->/,
          banner: '<!-- This file is automatically generated and should not be modified -->\n'
        }
      }
    }
  })

  grunt.loadNpmTasks('grunt-includes');
  grunt.registerTask('tests', ['includes']);
};
